#ifndef _NET_DEFINE_H
#define _NET_DEFINE_H

#include "define.h"

// 网络相关常量
const DWORD MAX_MAIN_THREAD_EVENT_NUM	= 3;
const DWORD INVALID_CONNECT_ID			= 0xFFFFFFFF;
const DWORD MAX_TIMER_NUM				= 1000;
const DWORD MAX_WORKER_THREAD_NUM		= 4;
const DWORD MAX_WSABUF_NUM_IN_SEND_FUNC	= 16;

// 网络ID类型
typedef DWORD NETWORK_ID;

// 连接状态枚举
enum CONNECTION_STATUS
{
	CONNECTION_STATUS_DISCONNECTED	= 0,
	CONNECTION_STATUS_CONNECTING	= 1,
	CONNECTION_STATUS_CONNECTED		= 2,
};

// 消息类型枚举
enum MSG_TYPE
{
	MSG_TYPE_NONE = 0,
	MSG_TYPE_CONNECT,
	MSG_TYPE_DISCONNECT,
	MSG_TYPE_DATA,
	MSG_TYPE_ACCEPT,
};

// Action Type枚举（用于消息容器头部）
enum ACTION_TYPE
{
	ACTION_TYPE_NONE			= 0x00000000,
	ACTION_TYPE_RECV_TCP		= 0x01000000,
	ACTION_TYPE_RECV_UDP		= 0x02000000,
	ACTION_TYPE_DISCONNECT		= 0x03000000,
	ACTION_TYPE_SWITCH_QUEUE	= 0x04000000,
	ACTION_TYPE_TCP				= 0x00000000,	// TCP连接类型
	ACTION_TYPE_DESTROY			= 0x05000000,	// 销毁动作
};

// Actor Type枚举
enum ACTOR_TYPE
{
	ACTOR_TYPE_NONE		= 0x00000000,
	ACTOR_TYPE_WORKER	= 0x10000000,
	ACTOR_TYPE_MAIN		= 0x20000000,
	ACTOR_TYPE_USER		= 0x30000000,
	ACTOR_TYPE_SERVER	= 0x40000000,
};

// 位掩码常量
const DWORD ACTION_TYPE_BIT_MASK			= 0x0F000000;
const DWORD ACTOR_TYPE_BIT_MASK				= 0xF0000000;
const DWORD CONNECTION_INDEX_BIT_MASK		= 0x00FFFFFF;
const DWORD INVERSE_ACTION_TYPE_BIT_MASK	= 0xF0FFFFFF;
const DWORD INVERSE_ACTOR_TYPE_BIT_MASK		= 0x0FFFFFFF;

// 数据包列表类型
struct PACKET_LIST
{
	DWORD	dwLen;			// 数据长度
	char*	pMsg;			// 消息数据（使用pMsg而非pData以兼容现有代码）
	PACKET_LIST* pNext;		// 下一个数据包
};

// 主线程事件索引枚举
enum MAIN_THREAD_EVENT_INDEX
{
	EVENT_INDEX_MSG_EVENT = 0,		// 消息事件
	EVENT_INDEX_DESTROY,			// 销毁事件
	EVENT_INDEX_BREAK,				// 中断事件
	EVENT_INDEX_RESUME,				// 恢复事件
	EVENT_INDEX_PRE_CONNECT,		// 预连接事件
	EVENT_INDEX_USER_DEFINE_0,		// 用户定义事件起始索引
};

// 主线程相关常量
const DWORD MIM_MAIN_THREAD_EVENT_NUM = 5;  // 最小主线程事件数量
const DWORD MAX_MAIN_THREAD_USER_DEFINE_EVENT_NUM = 1000;  // 最大用户定义事件数量

// 网络ID常量
const DWORD ID_NETWORK_FOR_USER = 0x10000000;
const DWORD ID_NETWORK_FOR_SERVER = 0x20000000;

// 网络调试标志常量
const DWORD NETDDSC_ENCRYPTION_MASK = 0x00000001;
const DWORD NETDDSC_ENCRYPTION = 0x00000001;
const DWORD NETDDSC_DEBUG_LOG_MASK = 0x00000002;
const DWORD NETDDSC_DEBUG_LOG = 0x00000002;

#endif
